### ISSUE TITLE
UI Design - Home

### ISSUE THREAD

**Issue by oberak** [oberak/home-automation#1]

**Comment by yethuaungptu** [comment]
assign UI design

**Comment by MyatThiri** [comment]
Drawing design

**Comment by ghost** [comment]
![ui1](https://user-images.githubusercontent.com/34784990/34324163-5ea299fc-e896-11e7-953b-538606485f20.png)

**Comment by ghost** [comment]
![222](https://user-images.githubusercontent.com/34784990/34324381-81769eac-e89f-11e7-8bca-180f64ea3f0a.png)
